class CONSTANTES {
    companion object{
        val ENERGIA_MINIMA = 1
        val ENERGIA_MAXIMA = 50
        var MAXIMO_ADVERSARIOS = 100
        var PROBABILIDAD_CANTIDAD_MAXIMA_ADVERSARIOS = 3
        var RESISTENCIA_GUARDIAN = 500
        var CANTIDAD_MAXIMA_CRISTALES_PURPURA = 6
        var PROBABILIDAD_ENCONTRAR_CRISTAL = 65
        var CANTIDAD_MAXIMA_ALMACEN_ADVERSARIO = 5
        var CANTIDAD_MAXIMA_CRISTALES_BASICOS = 494
        var CANTIDAD_CRISTALES_EXISTENTES = 500
    }
}